# Generated by Django 3.2.7 on 2021-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
